config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "sigab#index", as: "index"
  get "/fluxos", to: "sigab#fluxos", as: "fluxos"
  get "/fluxos/:id", to: "sigab#fluxo", as: "fluxo" 
  get "/saldo_ru", to: "sigab#saldo_ru", as: "saldo_ru" 
  get "/tabela_ru", to: "sigab#tabela_ru", as: "tabela_ru"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fluxo.rb
class Fluxo < ApplicationRecord
  serialize :nodes, Array
  serialize :links, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sigab_controller.rb
class SigabController < ActionController::Base
  def index

  end

  def fluxos
    @fluxos = Fluxo.all
  end

  def fluxo
    @fluxo = Fluxo.find(params[:id])
  end

  def saldo_ru
    
  end

  def tabela_ru

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sigab_helper.rb
module SigabHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sigab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sigab/fluxo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fluxograma - <%= @fluxo.curso %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= favicon_link_tag asset_path('logo_unb.svg') %>
  </head>

  <body>
    <div class="container-fluid text-center main" data-controller="graph">
      <div class="row main-top fluxo-top mx-0">
        <div class="col-2 d-flex flex-column justify-content-between">
          <div class="container text-start logo-unb" >
            <%= link_to index_path, :'data-controller' => "tooltip", :'data-bs-title' => "Voltar à página inicial" do %>
              <%= image_tag "logo_unb.svg", class: "img-thumbnail", alt: "logo-unb" %>
            <% end %>
          </div>
          <div class="card text-bg-light my-5">
            <div class="card-body">
              <h5 class="card-title">Instruções</h5>
              <div>
                <p><%= bootstrap_icon "arrows-move", class: "mx-2" %>Clique e arraste para se mover pelo fluxo</p>
                <p><%= bootstrap_icon "hand-index", class: "mx-2" %>Clique em uma das disciplinas para saber mais informações</p>
                <p><%= bootstrap_icon "zoom-in", class: "mx-2" %>Clique duas vezes na tela ou use o scroll do mouse para alterar o nível do zoom</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col align-self-center fluxo" data-graph-target="draw">
          <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
        <div class="col-2 align-self-end">
          <div class="card text-bg-light my-5">
            <div class="card-body">
              <h5 class="card-title">Legenda</h5>
              <h6 class="card-subtitle mb-2 text-muted">O que cada cor representa</h6>
              <div data-graph-target="labels">
                <p class="card-text placeholder-glow"><span class="placeholder col-8"></span></p>
                <p class="card-text placeholder-glow"><span class="placeholder col-8"></span></p>
                <p class="card-text placeholder-glow"><span class="placeholder col-8"></span></p>
                <p class="card-text placeholder-glow"><span class="placeholder col-8"></span></p>
              </div>
            </div>
          </div>
        </div>
        <%= tag :meta, name: :nodes, content: @fluxo.nodes.to_json %>
        <%= tag :meta, name: :links, content: @fluxo.links.to_json %>
      </div>
      <div class="row mx-0 justify-content-around align-items-center main-bottom fluxo-bottom">
        <div class="container text-center justify-content-center align-items-center d-flex py-2">
          <div class="card text-bg-light">
            <div class="card-body">
              <div>
                <%= link_to fluxos_path, class: "btn btn-danger" do %>
                  <%= bootstrap_icon "arrow-return-left" %> Voltar à pesquisa de fluxos
                <% end %>
                <% if @fluxo.id == 1 %>
                  <button type="button" class="btn btn-secondary" data-bs-toggle="button" data-action="click->graph#toggleHidden">
                    <%= bootstrap_icon "check-circle-fill" %> Esconder componentes concluídos
                  </button>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/sigab/fluxos.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIGAB - Fluxogramas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= favicon_link_tag asset_path('logo_unb.svg') %>
  </head>

  <body>
    <div class="container-fluid text-center main">
      <div class="row main-top fluxo-top mx-0">
        <div class="col-2 align-self-start">
          <div class="container text-start logo-unb" >
            <%= link_to index_path, :'data-controller' => "tooltip", :'data-bs-title' => "Voltar à página inicial" do %>
              <%= image_tag "logo_unb.svg", class: "img-thumbnail", alt: "logo-unb" %>
            <% end %>
          </div>
        </div>
        <div class="col align-self-start my-5" data-graph-target="draw">
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Nome do curso" aria-label="Nome do curso" aria-describedby="button-addon2">
            <button class="btn btn-dark disabled" type="button" id="button-addon2">Pesquisar <%= bootstrap_icon "search", class: "mx-1" %></button>
          </div>
          <div class="my-3 container resultados">
            <div class="row">
              <% @fluxos.each do |fluxo| %>
              <div class="col">
                <div class="container mt-5 text-center">
                  <div class="card text-bg-light">
                    <div class="card-body">
                      <h5 class="card-title"><%= fluxo.curso %></h5>
                      <div>
                        <%= link_to fluxo_path(fluxo.id), class: "btn btn-info my-2" do %>
                          <%= bootstrap_icon "diagram-3-fill" %> Fluxograma
                        <% end %>
                        <button type="button" class="btn btn-info disabled">
                          <%= bootstrap_icon "map-fill" %> Estrutura curricular
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-2 align-self-center"></div>
      </div>
      <div class="row mx-0 justify-content-around align-items-center main-bottom fluxo-bottom">
        <div class="container text-center justify-content-center align-items-center d-flex py-2">
          <div class="card text-bg-light">
            <div class="card-body">
              <div>
                <%= link_to index_path, class: "btn btn-danger" do %>
                  <%= bootstrap_icon "arrow-return-left" %> Voltar à página principal
                <% end %>
                <%= link_to fluxo_path(1), class: "btn btn-info" do %>
                  <%= bootstrap_icon "diagram-3-fill" %> Navegar pelo fluxograma do meu curso
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/sigab/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIGAB</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('logo_unb.svg') %>
  </head>

  <body>
    <div class="container-fluid text-center main">
      <div class="row main-top mx-0">
          <div class="col align-self-start">
            <div class="container text-start logo-unb">
              <%= link_to index_path do %>
                <%= image_tag "logo_unb.svg", class: "img-thumbnail", alt: "logo-unb" %>
              <% end %>
            </div>
          </div>
          <div class="col"></div>
          <div class="col align-self-center">
            <div class="container text-center user-profile">
              <div class="container">
                <%= image_tag "no_picture.png", class: "img-thumbnail", alt: "user-pic" %>
              </div>
              <div class="container nome-mat">
                <h3>Felipe Monte</h3>
                <h4>200289169</h4>
              </div>
              <div class="btn-group-vertical btn-group-lg" role="group" aria-label="Vertical button group">
                <%= link_to fluxos_path, class: "btn btn-light btn-lg" do %>
                  <%= bootstrap_icon "diagram-3-fill" %> Fluxos
                <% end %>
                <button type="button" class="btn btn-light btn-lg disabled">
                  <%= bootstrap_icon "briefcase-fill" %> Oferta
                </button>
                <%= link_to saldo_ru_path, class: "btn btn-light btn-lg" do %>
                  <%= bootstrap_icon "cup-hot-fill" %> Saldo RU
                <% end %>
              </div>
            </div>
          </div>
      </div>
      <div class="row mx-0 justify-content-around align-items-center main-bottom">
          <div class="col-5 turmas">
            <h2>Turmas</h2>
            <table class="table table-light">
              <thead>
                <tr>
                  <th scope="col">Componente curricular</th>
                  <th scope="col">Local</th>
                  <th scope="col">Horário</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><a href="#">Sistemas de Informação</a></td>
                  <td>PAT AT 029</td>
                  <td>35T23</td>
                </tr>
                <tr>
                  <td><a href="#">Engenharia de Software</a></td>
                  <td>PAT AT 037</td>
                  <td>35M12</td>
                </tr>
                <tr>
                  <td><a href="#">Introdução a Inteligência Artifical</a></td>
                  <td>PJC BT 036</td>
                  <td>24T23</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="col-5 text-center integralizacoes">
            <h2>Integralizações</h2>
            <table class="table table-light">
              <tbody>
                <tr>
                  <th scope="row">CH. Obrigatória Pendente</th>
                  <td>30h</td>
                </tr>
                <tr>
                  <th scope="row">CH. Optativa Pendente</th>
                  <td>30h</td>
                </tr>
                <tr>
                  <th scope="row">CH. Total Pendente</th>
                  <td>60h</td>
                </tr>
              </tbody>
            </table>
            <div class="progress" role="progressbar" aria-label="Integralizado" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="height: 24px">
              <div class="progress-bar bg-success" style="width: 70%">70% integralizado</div>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/sigab/saldo_ru.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIGAB - Saldo RU</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= favicon_link_tag asset_path('logo_unb.svg') %>
  </head>

  <body>
    <div class="container-fluid text-center main">
      <div class="row main-top fluxo-top mx-0">
        <div class="col-2 align-self-start">
          <div class="container text-start logo-unb" >
            <%= link_to index_path, :'data-controller' => "tooltip", :'data-bs-title' => "Voltar à página inicial" do %>
              <%= image_tag "logo_unb.svg", class: "img-thumbnail", alt: "logo-unb" %>
            <% end %>
          </div>
        </div>
        <div class="col align-self-center" data-graph-target="draw">
          <div class="container saldo-ru">
            <div class="card text-bg-light my-5">
              <div class="card-body">
                <h2 class="card-title">Saldo RU</h2>
                <div>
                  <h3>R$25,60</h3>
                </div>
              </div>
            </div>
            <div class="card text-bg-light my-5">
              <div class="card-body">
                <h2 class="card-title">Histórico</h2>
                <div>
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th scope="col">Data/Horário</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Valor</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>26/01/2022 às 18:34</td>
                        <td>Jantar (Grupo II)</td>
                        <th class="text-danger" scope="row">-R$6,10</th>
                      </tr>
                      <tr>
                        <td>26/01/2023 às 13:06</td>
                        <td>Almoço (Grupo II)</td>
                        <th class="text-danger" scope="row">-R$6,10</th>
                      </tr>
                      <tr>
                        <td>25/01/2022 às 18:02</td>
                        <td>Jantar (Grupo II)</td>
                        <th class="text-danger" scope="row">-R$6,10</th>
                      </tr>
                      <tr>
                        <td>24/01/2022 às 12:27</td>
                        <td>Almoço (Grupo II)</td>
                        <th class="text-danger" scope="row">-R$6,10</th>
                      </tr>
                      <tr>
                        <td>23/01/2023 às 18:16</td>
                        <td>Recarga</td>
                        <th class="text-success" scope="row">+R$50,00</th>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-2 align-self-center"></div>
      </div>
      <div class="row mx-0 justify-content-around align-items-center main-bottom fluxo-bottom">
        <div class="container text-center justify-content-center align-items-center d-flex py-2">
          <div class="card text-bg-light">
            <div class="card-body">
              <div>
                <%= link_to index_path, class: "btn btn-danger" do %>
                  <%= bootstrap_icon "arrow-return-left" %> Voltar à página principal
                <% end %>
                <%= link_to tabela_ru_path, class: "btn btn-info" do %>
                  <%= bootstrap_icon "currency-dollar" %> Tabela de preços RU
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/sigab/tabela_ru.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIGAB - Valores Refeições RU</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= favicon_link_tag asset_path('logo_unb.svg') %>
  </head>

  <body>
    <div class="container-fluid text-center main">
      <div class="row main-top fluxo-top mx-0">
        <div class="col-2 align-self-start">
          <div class="container text-start logo-unb" >
            <%= link_to index_path, :'data-controller' => "tooltip", :'data-bs-title' => "Voltar à página inicial" do %>
              <%= image_tag "logo_unb.svg", class: "img-thumbnail", alt: "logo-unb" %>
            <% end %>
          </div>
        </div>
        <div class="col align-self-center" data-graph-target="draw">
          <div class="container saldo-ru">
            <div class="card text-bg-light my-5">
              <div class="card-body">
                <h2 class="card-title">Valor das Refeições</h2>
                <div>
                  <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th scope="col" rowspan="2" class="align-middle">Refeição</th>
                        <th scope="col" colspan="4">Valor</th>
                      </tr>
                      <tr>
                        <th scope="col">Grupo I</th>
                        <th scope="col">Grupo II</th>
                        <th scope="col">Grupo III</th>
                        <th scope="col">Restaurante executivo</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Desjejum</td>
                        <td>Gratuito</td>
                        <td>R$2,85</td>
                        <td>R$7,05</td>
                        <td>R$49,90/kg</td>
                      </tr>
                      <tr>
                        <td>Almoço</td>
                        <td>Gratuito</td>
                        <td>R$6,10</td>
                        <td>R$15,20</td>
                        <td>R$49,90/kg</td>
                      </tr>
                      <tr>
                        <td>Jantar</td>
                        <td>Gratuito</td>
                        <td>R$6,10</td>
                        <td>R$15,20</td>
                        <td>R$49,90/kg</td>
                      </tr>
                    </tbody>
                  </table>
                  <h3>Grupos de acesso</h3>
                  <table class="table table-bordered">
                  <tbody>
                    <tr>
                      <th scope="row">Grupo I</th>
                      <td>Estudantes em vunerabilidade econômica (com renda familiar per capita inferior a 1,5 salário mínimo).</td>
                    </tr>
                    <tr>
                      <th scope="row">Grupo II</th>
                      <td>Estudantes que não estão em vunerabilidade econômica (com renda familiar per capita superior a 1,5 salário mínimo).</td>
                    </tr>
                    <tr>
                      <th scope="row">Grupo III</th>
                      <td>Servidores, terceirizados e visitantes em geral.</td>
                    </tr>
                  </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-2 align-self-center"></div>
      </div>
      <div class="row mx-0 justify-content-around align-items-center main-bottom fluxo-bottom">
        <div class="container text-center justify-content-center align-items-center d-flex py-2">
          <div class="card text-bg-light">
            <div class="card-body">
              <div>
                <%= link_to index_path, class: "btn btn-danger" do %>
                  <%= bootstrap_icon "arrow-return-left" %> Voltar à página principal
                <% end %>
                <%= link_to saldo_ru_path, class: "btn btn-info" do %>
                  <%= bootstrap_icon "wallet-fill" %> Checar saldo RU
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>